// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCd2lWuknSPvTTvML2wWMsaFGLRIdmG50Y',
    appId: '1:159525015491:web:e7c444763fe93abc28b776',
    messagingSenderId: '159525015491',
    projectId: 'task-verse-dc551',
    authDomain: 'task-verse-dc551.firebaseapp.com',
    storageBucket: 'task-verse-dc551.firebasestorage.app',
    measurementId: 'G-WD80QQ8YHX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAohVGQYpD9rSBVjJU9_8InALIkPbHhD7I',
    appId: '1:159525015491:android:484ac37e9db3682128b776',
    messagingSenderId: '159525015491',
    projectId: 'task-verse-dc551',
    storageBucket: 'task-verse-dc551.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB8aCuMhalsEWeNf0iwKk6arsolaXnnjww',
    appId: '1:159525015491:ios:ac447b92017f092428b776',
    messagingSenderId: '159525015491',
    projectId: 'task-verse-dc551',
    storageBucket: 'task-verse-dc551.firebasestorage.app',
    iosBundleId: 'com.example.taskverseMobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB8aCuMhalsEWeNf0iwKk6arsolaXnnjww',
    appId: '1:159525015491:ios:ac447b92017f092428b776',
    messagingSenderId: '159525015491',
    projectId: 'task-verse-dc551',
    storageBucket: 'task-verse-dc551.firebasestorage.app',
    iosBundleId: 'com.example.taskverseMobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCd2lWuknSPvTTvML2wWMsaFGLRIdmG50Y',
    appId: '1:159525015491:web:42b7103391dbd3c128b776',
    messagingSenderId: '159525015491',
    projectId: 'task-verse-dc551',
    authDomain: 'task-verse-dc551.firebaseapp.com',
    storageBucket: 'task-verse-dc551.firebasestorage.app',
    measurementId: 'G-KJF72LP678',
  );
}
